# language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jwbailey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jwbailey/docker-react npm run test
